### ISSUE TITLE
About the solder bridge SB10.

### ISSUE THREAD

**Issue by SimonWoodburyForget** [japaric/discovery#33]
A disclaimer on [06-hello-world](https://japaric.github.io/discovery/06-hello-world/README.html) says that "*you'll **have to solder** the solder bridge SB10"* to get to print anything with the printing macro for the itmdump.

It needs to be noted in the disclaimer that you don't have to solder anything at all. That you can just literally plug the last pin of the [SWD (CN3? idk..) into PB3](https://prasanndutt.com/2015/01/30/stm32f3-programming-and-debug-using-swo/) with some extra wires. 

The solder bridge SB10 is just a more permanent option, it's not *"required"*.

**Comment by japaric** [comment]
Thanks for the heads up. I have added an alternative to that section.
