### ISSUE TITLE
Unclear how to complete uprintln! example

### ISSUE THREAD

**Issue by acfoltzer** [japaric/discovery#38]
The sample we're meant to complete for `uprintln!` has us implementing the `Write` trait, but we don't have the `std` crate available to bring `std::fmt` into scope. Am I missing something here?

**Comment by japaric** [comment]
`Write` is actually defined in `core::fmt` and then re-exported in `std::fmt`. I'll add a note about that.

**Comment by japaric** [comment]
Added a note.
