### ISSUE TITLE
Target directory not clear in 05-led-roulette/build-it

### ISSUE THREAD

**Issue by WimbledonLabs** [japaric/discovery#66]
When executing the following from the `discovery/src/05-led-roulette` directory:

```xargo build --target thumbv7em-none-eabihf```

It's not clear the the resulting target is `discovery/target` since the previous page says "Now, jump into the `src/05-led-roulette directory`."

**Comment by japaric** [comment]
> It's not clear the the resulting target is discovery/target

Ah yes, this changed due to the last minute change of moving to workspaces. We could workaround the issue by commiting symlinks that point to discovery/target. Though, I'm unsure if that would work on Windows (probably not).

**Comment by WimbledonLabs** [comment]
Thanks for this tutorial! I was excited to see that you updated it. Things have been going well so far on Ubuntu 16.04 (minus some gdb weirdness that I need to look into).
